name: pipeline
on:
  push:
    branches: 
      - pipelines

jobs:
  sonarcloud-sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19

      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=rolandobracho_laboratorio-final \
            -Dsonar.organization=rolandobracho \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.javascript.node.version=19 \
            -Dsonar.sources=src \
            -Dsonar.projectName="laboratorio-final" \
            -Dsonar.projectVersion=1.0
      
      - name: Check SonarCloud Vulnerabilities
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          response=$(curl -s -X GET -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/issues/search?branch=pipelines&componentKeys=rolandobracho_laboratorio-final&facets=severities")
          count=$(curl -s -X GET -u "$SONAR_TOKEN:" "https://sonarcloud.io/api/issues/search?branch=pipelines&componentKeys=rolandobracho_laboratorio-final&facets=severities" | 
                  jq -r '[.facets[0].values[] | select(.val == "CRITICAL" or .val == "HIGH" or .val == "MEDIUM") | .count] | add // 0')
          echo "Respuesta completa de la API:"
          echo "$response" | jq .
          if [ "$count" -gt 0 ]; then
            echo "Vulnerabilidades encontradas (Critical/High/Medium): $count"
            exit 1
          else
            echo "No hay vulnerabilidades graves. Continuando..."
          fi
